---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。 
---
= すべてのクラウドプロバイダで制約があります
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このリリースの製品でサポートされていない、または正しく相互運用できないプラットフォーム、デバイス、または機能については、既知の制限事項が記載されています。これらの制限事項をよく確認してください。

すべてのクラウドプロバイダの Cloud Volumes ONTAP に、 AWS 、 Azure 、 Google Cloud の制限が適用されます。



== 最大同時レプリケーション処理数

Cloud Volumes ONTAP で同時に実行できる SnapMirror 転送または SnapVault 転送の最大数は、インスタンスのタイプやマシンのタイプに関係なく、ノードあたり 100 です。



== クラウドプロバイダの Snapshot をバックアップとリカバリの計画に使用しないでください

クラウドプロバイダのスナップショットは、 Cloud Volumes ONTAP データのバックアップとリカバリの計画には使用しないでください。Cloud Volumes ONTAP でホストされているデータのバックアップとリストアには、必ず ONTAP の Snapshot コピーや他社製のバックアップソリューションを使用してください。

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-backup-to-cloud.html["Cloud Backup Service を使用して ONTAP データをバックアップおよびリストアする方法について説明します"^]です。


NOTE: データの整合性は、 WAFL ファイルシステムの ONTAP 整合ポイントによって決まります。WAFL ファイルシステムを休止して crash-consistent バックアップを実行できるのは、 ONTAP のみです。



== Cloud Volumes ONTAP は、予約済みおよびオンデマンドの VM インスタンスをサポートします

Cloud Volumes ONTAP は、クラウドプロバイダから予約済みまたはオンデマンドの VM インスタンスのいずれかで実行できます。それ以外のタイプの VM インスタンスはサポートされません。



== 自動アプリケーションリソース管理ソリューションは使用しないでください

アプリケーションリソースの自動管理ソリューションでは、 Cloud Volumes ONTAP システムを管理しないでください。サポートされていない構成に変更される可能性があります。たとえば、このソリューションでは、 Cloud Volumes ONTAP をサポート対象外の VM インスタンスタイプに変更する場合があります。



== ソフトウェアの更新はBlueXPが完了している必要があります

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性



== から Cloud Volumes ONTAP 環境を変更することはできません クラウドプロバイダのコンソール

クラウドプロバイダのコンソールから Cloud Volumes ONTAP 構成を変更した場合、サポートされない構成になります。BlueXPが作成および管理するCloud Volumes ONTAP リソースに変更を加えると、システムの安定性とシステム管理能力に影響を与える可能性があります。



== ディスクとアグリゲートはBlueXPで管理する必要があります

すべてのディスクとアグリゲートは、BlueXPから直接作成および削除する必要があります。これらのアクションは、別の管理ツールから実行しないでください。これにより、システムの安定性が低下し、将来ディスクを追加できなくなる可能性があります。また、クラウドプロバイダの冗長料金が発生する可能性もあります。



== SnapManager のライセンスに関する制限

SnapManager のサーバ単位のライセンスは、 Cloud Volumes ONTAP でサポートされます。ストレージシステム（ SnapManager スイート）単位のライセンスはサポートされません。



== サポートされない ONTAP 機能です

Cloud Volumes ONTAP では、次の機能はサポートされていません。

* アグリゲートレベルのインライン重複排除
* アグリゲートレベルのバックグラウンド重複排除
* ランサムウェア対策
* ディスクメンテナンスセンター
* ディスク完全消去
* FabricPool ミラーリング
* ファイバチャネル（FC）
* Flash Pool
* Infinite Volume
* インターフェイスグループ
* ノード内の LIF のフェイルオーバー
* MetroCluster
* マルチ管理者認証
+
Cloud Volumes ONTAP でマルチ管理者検証を有効にすると、構成がサポートされなくなります。

* Google CloudのONTAP S3（S3プロトコルはAzureとAWSでサポート）
* RAID 4 、 RAID-DP 、 RAID-TEC （ RAID 0 のサポート）
* サービスプロセッサ
* SnapLock のコンプライアンスモードとエンタープライズモード（クラウドの WORM のみサポート）
* SnapMirror Synchronous
* VLAN

