---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0には、新しい機能拡張が含まれています。 
---
= Cloud Volumes ONTAP 9.12.0の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0には、新しい機能拡張が含まれています。

その他の機能と拡張機能も、最新バージョンのBlueXPで導入されました。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXPリリースノート"^]詳細については、を参照してください。



== 9.12.0 P1（2022年12月15日）

Cloud Volumes ONTAP 9.12.0 P1がAWSとGoogle Cloudで利用できるようになりました。このリリースの新機能は次のとおりです。



=== AWS で m6id.32xlarge をサポートしています

AWSのm6id.32xlarge EC2インスタンスタイプでCloud Volumes ONTAPがサポートされるようになりました。

詳細については、を参照してlink:reference-configs-aws.html["[ サポートされている構成 ] ページ"]ください。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、以下のメモをお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは、BlueXPから完了している必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響を与える可能性

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["BlueXPから通知があった場合のアップグレード方法について説明します"^]です。



=== サポートされるアップグレードパス

Cloud Volumes ONTAP 9.11.1リリースから9.12.0にアップグレードできます。BlueXPでは、対象となるCloud Volumes ONTAP システムをこのリリースにアップグレードするように求められます。



=== 必要なコネクタのバージョン

新しいCloud Volumes ONTAP 9.12.0システムを導入し、既存のシステムをこのリリースにアップグレードするには、BlueXP  Connectorのバージョン3.9.24以降が実行されている必要があります。


TIP: コネクタの自動アップグレードはデフォルトで有効になっているため、最新バージョンを実行する必要があります。



=== ダウンタイム

* シングルノードシステムのアップグレードでは、 I/O が中断されるまで最大 25 分間システムがオフラインになります。
* HA ペアのアップグレードは無停止で、 I/O が中断されません。無停止アップグレードでは、各ノードが連携してアップグレードされ、クライアントへの I/O の提供が継続されます。




=== C4、M4、R4 EC2インスタンスタイプを使用したAWSでのアップグレード

AWSでは、新しいCloud Volumes ONTAP環境でc4、m4、およびr4 EC2インスタンスタイプはサポートされなくなりました。C4、M4、またはR4インスタンスタイプで実行されている既存のシステムがある場合は、C5、m5、またはr5インスタンスファミリーでインスタンスタイプに変更する必要があります。インスタンスタイプを変更できない場合は、アップグレード前に拡張ネットワークを有効にする必要があります。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["C4、M4、R4 EC2インスタンスタイプを使用してAWSでアップグレードする方法を確認する"^]です。link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Cloud Volumes ONTAP のEC2インスタンスタイプを変更する方法について説明します"^]です。

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetAppのサポート"^]これらのインスタンスタイプの販売終了とサポート終了の詳細については、を参照してください。
